#!/bin/sh

SESSIONNAME=rtl_tcp
LISTEN_ADDRESS=127.0.0.1

if ! tmux has-session -t $SESSIONNAME >/dev/null 2>&1 ; then
    tmux new-session -s $SESSIONNAME -d
    tmux send-keys -t $SESSIONNAME "rtl_tcp -a $LISTEN_ADDRESS" C-m
fi
