#!/usr/bin/env python3

import argparse
import json
import re
import subprocess
from datetime import datetime
from urllib import request


DEFAULT_URL =  'http://127.0.0.1:8080/telegraf'
METER_TIME_REGEX = r'^([^.]+)\.(\d+)([+-].*)$'
METER_TIME_FORMAT = '%Y-%m-%dT%H:%M:%S%z'
# Ignore any consumption spike this number or higher. The units are Wh so
# over a five minute window this is 120 kWh usage.
CONSUMPTION_SPIKE_IGNORE = 10000


class Rtlamr:

    TIME_RE = re.compile(METER_TIME_REGEX)

    def __init__(self, filterid=None, msgtype=None, rtl_tcp_server=None):
        self.filterid = filterid
        self.msgtype = msgtype
        self.rtl_tcp_server = rtl_tcp_server

    def run(self):
        rtlamr_cmd = ['rtlamr', '-format', 'json']
        if self.rtl_tcp_server:
            rtlamr_cmd.extend(['-server', self.rtl_tcp_server])
        if self.filterid:
            rtlamr_cmd.extend(['-filterid', self.filterid])
        if self.msgtype:
            rtlamr_cmd.extend(['-msgtype', self.msgtype])
        rtlamr = subprocess.Popen(rtlamr_cmd, stdout=subprocess.PIPE,
                                  stderr=subprocess.PIPE)

        while True:
            sample_bytes = rtlamr.stdout.readline()
            if not sample_bytes:
                continue
            sample_line = sample_bytes.decode('utf-8')
            try:
                meter_reading = json.loads(sample_line)
            except json.decoder.JSONDecodeError:
                print(f"Failed to decode: {sample_line}", flush=True)
                continue
            msgtype = meter_reading['Type']
            msg_time = self._parse_msg_time(meter_reading['Time'])
            if msg_time is None:
                print(f"Failed to match against time '{meter_reading['Time']}'", flush=True)
                continue
            # Send consumption count to URL.
            if msgtype == 'SCM' or msgtype == 'SCM+':
                consumption_count = self._parse_scm(meter_reading)
            elif msgtype == 'IDM':
                consumption_count = self._parse_idm(meter_reading)
            else:
                print(f"Unknown message type: {msgtype}", flush=True)
                continue
            yield msg_time, consumption_count

    @staticmethod
    def _parse_idm(idm_msg):
        consumption_count = int(idm_msg['Message']['LastConsumptionCount'])
        return consumption_count

    @staticmethod
    def _parse_scm(scm_msg):
        consumption_count = scm_msg['Message']['Consumption']
        return consumption_count

    def _parse_msg_time(self, timestamp):
        # "Time":"2019-06-30T21:03:08.177893784-04:00"
        time_match = self.TIME_RE.match(timestamp)
        if not time_match:
            return
        meter_strtime = time_match.group(1) + time_match.group(3).replace(':', '')
        meter_time = datetime.strptime(meter_strtime, METER_TIME_FORMAT)
        return meter_time


def send_meter_read(url, timestamp, meter_read, dry_run=False):
    meter_influxdb = f'electric usage={meter_read}i {timestamp}'
    if not dry_run:
        meter_influxdb_bytes = meter_influxdb.encode('utf-8')
        req = request.Request(url, data=meter_influxdb_bytes)
        resp = request.urlopen(req)
    else:
        print(f"Sending '{meter_influxdb}' to {url}", flush=True)


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--filterid', '-I', help="Filter on this meter ID")
    parser.add_argument('--msgtype', '-T', help="Filter on this message type")
    parser.add_argument('--server', '-s', help="rtl_tcp server")
    parser.add_argument('--url', '-u', help="Telegraf URL")
    parser.add_argument('--dry-run', '-n', action='store_true', default=False,
                        help="dry-run mode")
    parser.add_argument('--verbose', '-v', action='store_true', default=False,
                        help="Verbose mode")
    args = parser.parse_args()
    return args


def main():
    args = parse_args()
    url = args.url or DEFAULT_URL

    time_re = re.compile(METER_TIME_REGEX)
    last_consumption = -1
    rtlamr = Rtlamr(args.filterid, args.msgtype, args.server)
    for msg_time, consumption_count in rtlamr.run():
        if args.verbose:
            print(f"Received consumption usage of {consumption_count}", flush=True)
        consumption_change = consumption_count - last_consumption
        if consumption_count >= 2**31:
            # Read error from the meter.
            print("Failed to get sensical consumption count.", flush=True)
            continue
        elif last_consumption == consumption_count:
            continue
        elif last_consumption > consumption_count:
            print("Consumption count went backwards, skipping", flush=True)
            continue
        elif last_consumption > 0 and consumption_change > CONSUMPTION_SPIKE_IGNORE:
            print(f"Large consumption spike detected ({consumption_change}), skipping", flush=True)
            continue
        # Force nanoseconds to zero. Including nanoseconds adds false precision
        # to the reading. Already it only updates every 60 seconds at best and
        # often only has new values every five minutes. Skipping nanoseconds
        # allows InfluxDB to possibly compress the values better without nine
        # random digits attached to every reading.
        timestamp = f'{int(msg_time.timestamp())}000000000'
        send_meter_read(url, timestamp, consumption_count, dry_run=args.dry_run)
        last_consumption = consumption_count


if __name__ == '__main__':
    main()
